//! Wire-level data structures for the TRAINS protocol.
//!
//! These types map directly to the TLA+ variables in TRAINS.tla:
//!
//!   TLA+ `tr[t]`   →  [`Train`]
//!   TLA+ `Payload` →  [`Payload`]
//!   TLA+ `Procs`   →  process IDs 0..RING_SIZE

use serde::{Deserialize, Serialize};

// RING_SIZE and NUM_TRAINS are generated by build.rs from env vars
// TRAINS_RING_SIZE / TRAINS_NUM_TRAINS (default: 3 / 2).
include!(concat!(env!("OUT_DIR"), "/ring_config.rs"));

/// Process identifier — supports rings up to 30 nodes.
pub type ProcId = u8;

/// Logical clock value.  u64 never overflows in practice; we use
/// checked_add to satisfy Kani's arithmetic-safety harness.
pub type Tick = u64;

/// Bit-mask: bit i set ⟺ process i has acked this train.
/// u32 supports rings up to 30 nodes; wire size increases by 3 bytes
/// vs the original u8 (acceptable for benchmarking at any ring size).
pub type AckBits = u32;

/// Complete ack mask when all RING_SIZE processes have acked.
pub const FULL_ACK: AckBits = (1u32 << RING_SIZE) - 1;

/// A single application-level payload.
///
/// Maps to one element of `tr[t].msgs` in TRAINS.tla.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct Payload {
    /// Process that broadcast this payload.
    pub sender: ProcId,
    /// Monotonically increasing per-sender sequence number.
    pub seq: u64,
    /// Raw application bytes.
    pub data: Vec<u8>,
}

/// A TRAINS token-train — the unit of circulation in the ring.
///
/// Corresponds to a single `tr[t]` record in TRAINS.tla.
///
/// ## Field mapping (TLA+ → Rust)
/// | TLA+ field        | Rust field    |
/// |-------------------|---------------|
/// | `tr[t].issuer`    | `issuer`      |
/// | `tr[t].clock`     | `clock`       |
/// | `tr[t].msgs`      | `payloads`    |
/// | `tr[t].acks`      | `ack_bits`    |
/// | `tr[t].pos`       | (implicit: which node currently holds the train) |
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Train {
    /// Process that created this train slot.
    pub issuer: ProcId,
    /// Logical clock — strictly increasing per issuer.
    /// Used for: delivery ordering, clock-gap crash detection.
    pub clock: Tick,
    /// Payloads accumulated during this ring tour.
    pub payloads: Vec<Payload>,
    /// Bit-mask of processes that have processed this train.
    /// When `ack_bits == FULL_ACK`, all processes have acked.
    pub ack_bits: AckBits,
}

impl Train {
    /// Returns true when all RING_SIZE processes have acknowledged this train.
    /// This is the UTO delivery condition (TLA+: `tr[t].acks = Procs`).
    #[inline]
    pub fn is_fully_acked(&self) -> bool {
        self.ack_bits == FULL_ACK
    }

    /// Returns true if process `id` has already acked this train.
    #[inline]
    pub fn is_acked_by(&self, id: ProcId) -> bool {
        self.ack_bits & (1u32 << u32::from(id)) != 0
    }

    /// Records an ack from process `id`.
    #[inline]
    pub fn add_ack(&mut self, id: ProcId) {
        self.ack_bits |= 1u32 << u32::from(id);
    }

    /// The (clock, issuer) ordering key used for total-order delivery.
    /// Corresponds to `ClockKey(cl, iss)` in TRAINS.tla.
    #[inline]
    pub fn clock_key(&self) -> (Tick, ProcId) {
        (self.clock, self.issuer)
    }
}
